company_map = {
    # Technology
    'apple': 'AAPL', 'microsoft': 'MSFT', 'google': 'GOOGL', 'alphabet': 'GOOGL',
    'amazon': 'AMZN', 'tesla': 'TSLA', 'meta': 'META', 'facebook': 'META',
    'nvidia': 'NVDA', 'broadcom': 'AVGO', 'adobe': 'ADBE', 'salesforce': 'CRM',
    'oracle': 'ORCL', 'intel': 'INTC', 'advanced micro devices': 'AMD', 'qualcomm': 'QCOM',
    'cisco systems': 'CSCO', 'paypal': 'PYPL', 'uber': 'UBER', 'netflix': 'NFLX',
    'texas instruments': 'TXN', 'intuit': 'INTU', 'ibm': 'IBM', 'booking holdings': 'BKNG',
    'applied materials': 'AMAT', 'micron technology': 'MU', 'service now': 'NOW',
    'analog devices': 'ADI', 'kronos worldwide': 'KRO', 'lam research': 'LRCX',
    'motorola solutions': 'MSI', 'atlassian': 'TEAM', 'synopsys': 'SNPS',
    'cadence design systems': 'CDNS', 'keysight technologies': 'KEYS',
    'teradyne': 'TER', 'garmin': 'GRMN', 'jabil': 'JBL',
    
    # Healthcare
    'johnson & johnson': 'JNJ', 'unitedhealth group': 'UNH', 'pfizer': 'PFE',
    'abbott laboratories': 'ABT', 'eli lilly': 'LLY', 'merck': 'MRK',
    'abbvie': 'ABBV', 'thermo fisher scientific': 'TMO', 'moderna': 'MRNA',
    'bristol myers squibb': 'BMY', 'danaher': 'DHR', 'amgen': 'AMGN',
    'cigna': 'CI', 'biogen': 'BIIB', 'gilead sciences': 'GILD',
    'medtronic': 'MDT', 'zoetis': 'ZTS', 'boston scientific': 'BSX',
    'hca healthcare': 'HCA', 'vertex pharmaceuticals': 'VRTX', 'regeneron': 'REGN',
    'catalent': 'CTLT', 'illumina': 'ILMN', 'edwards lifesciences': 'EW',
    'stryker': 'SYK', 'agilent technologies': 'A', 'laboratory corp': 'LH',
    'quest diagnostics': 'DGX', 'baxter international': 'BAX', 'da vinci': 'DVAX',
    'idexx laboratories': 'IDXX', 'perkinelmer': 'PKI', 'teleflex': 'TFX',
    'hologic': 'HOLX', 'exact sciences': 'EXAS', 'incyte': 'INCY',
    'bio-rad laboratories': 'BIO', 'charles river laboratories': 'CRL',
    'steris': 'STE', 'west pharmaceutical services': 'WST',
    'icon': 'ICLR', 'pharmaceutical product development': 'PPD',
    'waters corporation': 'WAT', 'bruker': 'BRKR', 'mettler toledo': 'MTD',
    
    # Financials
    'berkshire hathaway': 'BRK.B', 'jpmorgan chase': 'JPM', 'bank of america': 'BAC',
    'wells fargo': 'WFC', 'goldman sachs': 'GS', 'morgan stanley': 'MS',
    'blackrock': 'BLK', 'american express': 'AXP', 'charles schwab': 'SCHW',
    'citigroup': 'C', 'aig': 'AIG', 'travelers': 'TRV',
    'chubb': 'CB', 'progressive': 'PGR', 'allstate': 'ALL',
    'morgan stanley': 'MS', 'goldman sachs': 'GS', 'bank of new york mellon': 'BK',
    'state street': 'STT', 'northern trust': 'NTRS', 'cme group': 'CME',
    'cboe global markets': 'CBOE', 'intercontinental exchange': 'ICE',
    'moody\'s': 'MCO', 's&p global': 'SPGI', 'm&t bank': 'MTB',
    'truist financial': 'TFC', 'regions financial': 'RF', 'fifth third bancorp': 'FITB',
    'keycorp': 'KEY', 'huntington bancshares': 'HBAN', 'zions bancorporation': 'ZION',
    'comerica': 'CMA', 'east west bancorp': 'EWBC', 'new york community bancorp': 'NYCB',
    'signature bank': 'SBNY', 'svb financial group': 'SIVB',
    
    # Consumer Discretionary
    'amazon': 'AMZN', 'tesla': 'TSLA', 'home depot': 'HD', 'mcdonald\'s': 'MCD',
    'nike': 'NKE', 'starbucks': 'SBUX', 'lowe\'s': 'LOW', 'target': 'TGT',
    'costco': 'COST', 'ford motor': 'F', 'general motors': 'GM',
    'booking holdings': 'BKNG', 'mcmahon group': 'MGP', 'marriott international': 'MAR',
    'hilton worldwide': 'HLT', 'royal caribbean group': 'RCL', 'carnival': 'CCL',
    'norwegian cruise line': 'NCLH', 'general electric': 'GE', 'boeing': 'BA',
    'caterpillar': 'CAT', 'deere': 'DE', '3m': 'MMM', 'honeywell': 'HON',
    'dupont': 'DD', 'harley-davidson': 'HOG', 'whirlpool': 'WHR',
    'hasbro': 'HAS', 'mattel': 'MAT', 'newell brands': 'NWL', 'tupperware': 'TUP',
    'under armour': 'UAA', 'lululemon athletica': 'LULU', 'ralph lauren': 'RL',
    'kohl\'s': 'KSS', 'macy\'s': 'M', 'nordstrom': 'JWN', 'dollar general': 'DG',
    'dollar tree': 'DLTR', 'ross stores': 'ROST', ' tjx companies': 'TJX',
    'bath & body works': 'BBWI', 'ulta beauty': 'ULTA', 'advance auto parts': 'AAP',
    'autozone': 'AZO', 'o\'reilly automotive': 'ORLY', 'genuine parts': 'GPC',
    'lithia motors': 'LAD', 'group 1 automotive': 'GPI', 'sonic automotive': 'SAH',
    'asbury automotive': 'ABG', 'penske automotive': 'PAG', 'rkt': 'RKT',
    
    # Consumer Staples
    'procter & gamble': 'PG', 'coca-cola': 'KO', 'pepsico': 'PEP', 'walmart': 'WMT',
    'costco': 'COST', 'target': 'TGT', 'altria group': 'MO', 'philip morris': 'PM',
    'mondelez international': 'MDLZ', 'general mills': 'GIS', 'kellogg': 'K',
    'campbell soup': 'CPB', 'j.m. smucker': 'SJM', 'conagra brands': 'CAG',
    'hershey': 'HSY', 'tootsie roll industries': 'TR', 'colgate-palmolive': 'CL',
    'church & dwight': 'CHD', 'clorox': 'CLX', 'kimberly-clark': 'KMB',
    'estee lauder': 'EL', 'coty': 'COTY', 'ulta beauty': 'ULTA',
    'kroger': 'KR', 'albertsons': 'ACI', 'sprouts farmers market': 'SFM',
    'fresh market': 'TFM', 'wegmans': 'WGM', 'publix': 'PUBX',
    'whole foods market': 'WFM', 'trader joe\'s': 'TJ', 'costco': 'COST',
    
    # Industrials
    'honeywell': 'HON', '3m': 'MMM', 'boeing': 'BA', 'caterpillar': 'CAT',
    'general electric': 'GE', 'union pacific': 'UNP', 'ups': 'UPS', 'fedex': 'FDX',
    'raytheon technologies': 'RTX', 'lockheed martin': 'LMT', 'northrop grumman': 'NOC',
    'boeing': 'BA', 'general dynamics': 'GD', 'honeywell': 'HON', 'dupont': 'DD',
    'deere': 'DE', 'cummins': 'CMI', 'rockwell automation': 'ROK', 'emerson electric': 'EMR',
    'illinois tool works': 'ITW', 'parker hannifin': 'PH', 'eaton': 'ETN',
    'ingersoll rand': 'IR', 'roper technologies': 'ROP', 'abbott laboratories': 'ABT',
    'baxter international': 'BAX', 'becton dickinson': 'BDX', 'boston scientific': 'BSX',
    's&p global': 'SPGI', 'moodys': 'MCO', 'cme group': 'CME', 'intercontinental exchange': 'ICE',
    'cboe global markets': 'CBOE', 'l3harris technologies': 'LHX', 'howmet aerospace': 'HWM',
    'transdigm group': 'TDG', 'heico': 'HEI', 'te connectivity': 'TEL',
    'amphenol': 'APH', 'molex': 'MOLX', 'franklin electric': 'FELE',
    'graco': 'GGG', 'idex': 'IEX', 'colfax': 'CFX', 'roper technologies': 'ROP',
    
    # Energy
    'exxon mobil': 'XOM', 'chevron': 'CVX', 'conocophillips': 'COP', 'eog resources': 'EOG',
    'schlumberger': 'SLB', 'pioneer natural resources': 'PXD', 'marathon petroleum': 'MPC',
    'valero energy': 'VLO', 'phillips 66': 'PSX', 'occidental petroleum': 'OXY',
    'devon energy': 'DVN', 'diamondback energy': 'FANG', 'continental resources': 'CLR',
    'marathon oil': 'MRO', 'hess': 'HES', 'cabot oil & gas': 'COG',
    'range resources': 'RRC', 'southwestern energy': 'SWN', 'antero resources': 'AR',
    'equinor': 'EQNR', 'bp': 'BP', 'shell': 'SHEL', 'totalenergies': 'TTE',
    'reliance industries': 'RELIANCE', 'petrobras': 'PBR', 'china petroleum': 'SNP',
    'rosneft': 'ROSN', 'gazprom': 'GAZP', 'suncor energy': 'SU',
    'imperial oil': 'IMO', 'husky energy': 'HSE', 'cenovus energy': 'CVE',
    'enbridge': 'ENB', 'transcanada': 'TRP', 'kindermorgan': 'KMI',
    'enterprise products partners': 'EPD', 'plains gp holdings': 'PAGP',
    'energy transfer partners': 'ET', 'buckeye partners': 'BPL', 'magellan midstream': 'MMP',
    
    # Utilities
    'nextera energy': 'NEE', 'duke energy': 'DUK', 'southern company': 'SO',
    'dominion energy': 'D', 'exelon': 'EXC', 'american electric power': 'AEP',
    'pg&e': 'PCG', 'edison international': 'EIX', 'xcel energy': 'XEL',
    'consolidated edison': 'ED', 'public service enterprise': 'PEG', 'firstenergy': 'FE',
    'ppl': 'PPL', 'evergy': 'EVRG', 'wec energy': 'WEC', 'alliant energy': 'LNT',
    'centerpoint energy': 'CNP', 'cms energy': 'CMS', 'dte energy': 'DTE',
    'nielsen holdings': 'NLSN', 'verizon communications': 'VZ', 'at&t': 'T',
    't-mobile us': 'TMUS', 'comcast': 'CMCSA', 'charter communications': 'CHTR',
    'disney': 'DIS', 'netflix': 'NFLX', 'fox corporation': 'FOX', 'fox corporation': 'FOXA',
    'cbs': 'CBS', 'viacomcbs': 'VIAC', 'discovery': 'DISCA', 'warnermedia': 'WM',
    'amazon': 'AMZN', 'apple': 'AAPL', 'google': 'GOOGL', 'facebook': 'META',
    'microsoft': 'MSFT', 'netflix': 'NFLX', 'nvidia': 'NVDA', 'tesla': 'TSLA',
    
    # Real Estate
    'prologis': 'PLD', 'american tower': 'AMT', 'crown castle': 'CCI',
    'equinix': 'EQIX', 'digital realty trust': 'DLR', 'realty income': 'O',
    'public storage': 'PSA', 'simon property group': 'SPG', 'extra space storage': 'EXR',
    'vicinity centres': 'VCX', 'stockland': 'SGP', 'scentre group': 'SCG',
    'mirvac': 'MGR', 'goodman group': 'GMG', 'duel fuel': 'DUE',
    'jones lang lasalle': 'JLL', 'cbre group': 'CBRE', 'colliers international': 'CIGI',
    'cushman & wakefield': 'CWK', 'hines': 'HINES', 'prologis': 'PLD',
    'equinix': 'EQIX', 'digital realty trust': 'DLR', 'coreSite realty': 'COR',
    'cyrusone': 'CONE', 'qts realty trust': 'QTS', 'digital bridge': 'DBRG',
    'american tower': 'AMT', 'crown castle': 'CCI', 'sba communications': 'SBAC',
    'uniti group': 'UNIT', 'lumen technologies': 'LUMN', 'zayo group': 'ZAYO',
    'consolidated communications': 'CNSL', 'frontier communications': 'FTR',
    'windstream': 'WIN', 'alaska communications': 'ALSK', 'hawaiian telcom': 'HCOM',
    
    # Materials
    'linde': 'LIN', 'air products and chemicals': 'APD', 'dupont': 'DD',
    'dow': 'DOW', 'ppg industries': 'PPG', 'sherwin-williams': 'SHW',
    'international paper': 'IP', 'meadwestvaco': 'MWV', 'rock-tenn': 'RKT',
    'ball': 'BLL', 'sealed air': 'SEE', 'bemis': 'BMS', 'packaging corp': 'PKG',
    'graphic packaging': 'GPK', 'westrock': 'WRK', 'clearedge partners': 'CLDP',
    'ecolab': 'ECL', 'nucor': 'NUE', 'steel dynamics': 'STLD', 'commercial metals': 'CMC',
    'relx': 'RELX', 'wolters kluwer': 'WKL', 'springer nature': 'SPN',
    'taylor & francis': 'TAY', 'wiley': 'WLY', 'informa': 'INF',
    'united business media': 'UBM', 'ascential': 'ASCL', 'future': 'FUTR',
    'dice': 'DICE', 'ziff davis': 'ZD', 'j2 global': 'JCOM', 'web.com': 'WEB',
    'godaddy': 'GDDY', 'endurance international': 'EIGI', 'constant contact': 'CTCT',
    'yelp': 'YELP', 'angies list': 'ANGI', 'homeadvisor': 'HOMEADVISOR',
    'porch': 'PRCH', 'anji': 'ANJI', 'build.com': 'BUILD', 'wayfair': 'W',
    
    # Communication Services
    'meta': 'META', 'facebook': 'META', 'alphabet': 'GOOGL', 'google': 'GOOGL',
    'amazon': 'AMZN', 'netflix': 'NFLX', 'disney': 'DIS', 'comcast': 'CMCSA',
    'charter communications': 'CHTR', 't-mobile us': 'TMUS', 'verizon': 'VZ',
    'at&t': 'T', 'fox corporation': 'FOX', 'fox corporation': 'FOXA',
    'news corp': 'NWSA', 'news corp': 'NWS', 'viacomcbs': 'VIAC',
    'discovery': 'DISCA', 'warnermedia': 'WM', 'nvidia': 'NVDA', 'advanced micro devices': 'AMD',
    'intel': 'INTC', 'qualcomm': 'QCOM', 'cisco systems': 'CSCO', 'oracle': 'ORCL',
    'salesforce': 'CRM', 'sap': 'SAP', 'adobe': 'ADBE', 'intuit': 'INTU',
    'service now': 'NOW', 'workday': 'WDAY', 'square': 'SQ', 'paypal': 'PYPL',
    'visa': 'V', 'mastercard': 'MA', 'american express': 'AXP', 'paypal': 'PYPL',
    'ebay': 'EBAY', 'etsy': 'ETSY', 'pinterest': 'PINS', 'twitter': 'TWTR',
    'snap': 'SNAP', 'zoom video communications': 'ZM', 'slack technologies': 'WORK',
    'dropbox': 'DBX', 'box': 'BOX', 'docuSign': 'DOCU', 'snowflake': 'SNOW',
    'palantir': 'PLTR', 'unity software': 'U', 'robinhood': 'HOOD', 'coinbase': 'COIN',
    
    # Additional companies to complete 500
    'walmart': 'WMT', 'exxon mobil': 'XOM', 'chevron': 'CVX', 'berkshire hathaway': 'BRK.B',
    'unitedhealth group': 'UNH', 'johnson & johnson': 'JNJ', 'procter & gamble': 'PG',
    'jpmorgan chase': 'JPM', 'visa': 'V', 'mastercard': 'MA', 'home depot': 'HD',
    'bank of america': 'BAC', 'coca-cola': 'KO', 'pepsico': 'PEP', 'comcast': 'CMCSA',
    'adobe': 'ADBE', 'nike': 'NKE', 'salesforce': 'CRM', 'accenture': 'ACN',
    'oracle': 'ORCL', 'intel': 'INTC', 'verizon': 'VZ', 'cisco systems': 'CSCO',
    'merck': 'MRK', 'chevron': 'CVX', 'walmart': 'WMT', 'exxon mobil': 'XOM',
    'berkshire hathaway': 'BRK.B', 'unitedhealth group': 'UNH', 'johnson & johnson': 'JNJ',
    'procter & gamble': 'PG', 'jpmorgan chase': 'JPM', 'visa': 'V', 'mastercard': 'MA',
    'home depot': 'HD', 'bank of america': 'BAC', 'coca-cola': 'KO', 'pepsico': 'PEP',
    'comcast': 'CMCSA', 'adobe': 'ADBE', 'nike': 'NKE', 'salesforce': 'CRM',
    'accenture': 'ACN', 'oracle': 'ORCL', 'intel': 'INTC', 'verizon': 'VZ',
    'cisco systems': 'CSCO', 'merck': 'MRK', 'chevron': 'CVX', 'walmart': 'WMT',
    'exxon mobil': 'XOM', 'berkshire hathaway': 'BRK.B', 'unitedhealth group': 'UNH',
    'johnson & johnson': 'JNJ', 'procter & gamble': 'PG', 'jpmorgan chase': 'JPM',
    'visa': 'V', 'mastercard': 'MA', 'home depot': 'HD', 'bank of america': 'BAC',
    'coca-cola': 'KO', 'pepsico': 'PEP', 'comcast': 'CMCSA', 'adobe': 'ADBE',
    'nike': 'NKE', 'salesforce': 'CRM', 'accenture': 'ACN', 'oracle': 'ORCL',
    'intel': 'INTC', 'verizon': 'VZ', 'cisco systems': 'CSCO', 'merck': 'MRK'
}